# Generated by Django 3.2.8 on 2021-10-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0002_alter_machine_max_capacity'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TripStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('queue', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_station_links', to='directory.station')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_station_links', to='trips.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='stations',
            field=models.ManyToManyField(through='trips.TripStation', to='directory.Station'),
        ),
        migrations.AddField(
            model_name='trip',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='machines.machine'),
        ),
    ]
